//+------------------------------------------------------------------+
//|                                           Strategy_EURUSD.mq4 |
//|                                  Generated by Strategy Converter |
//+------------------------------------------------------------------+
#property copyright "FxMath Quant"
#property link      "https://fxmath.com"
#property version   "1.00"
#property strict

// Input Parameters
input double LotSize = 0.01;              // Lot Size
input int    ATR_Period = 30;   // ATR Period
input double SL_Multiplier = 4.79;  // Stop Loss Multiplier
input double TP_Multiplier = 8.10;  // Take Profit Multiplier
input int    MagicNumber = 12345;         // Magic Number
input string TradeComment = "Strategy_EURUSD";  // Trade Comment

// Global Variables
int atrHandle;
double atrValue;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{
    Print("Strategy EA initialized for EURUSD");
    return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
    Print("Strategy EA deinitialized");
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{
    // Calculate ATR
    atrValue = iATR(Symbol(), 0, ATR_Period, 1);
    
    // Check for open positions
    bool hasPosition = false;
    for(int i = OrdersTotal() - 1; i >= 0; i--)
    {
        if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
            if(OrderSymbol() == Symbol() && OrderMagicNumber() == MagicNumber)
            {
                hasPosition = true;
                break;
            }
        }
    }
    
    // If no position, check for entry signals
    if(!hasPosition)
    {
        // Check Buy Signal
        if(CheckBuySignal())
        {
            OpenBuyOrder();
        }
        // Check Sell Signal
        else if(CheckSellSignal())
        {
            OpenSellOrder();
        }
    }
}

//+------------------------------------------------------------------+
//| Check Buy Signal                                                 |
//+------------------------------------------------------------------+
bool CheckBuySignal()
{
    return (Open[1] < Close[6] &&
            High[9] >= Close[3] &&
            Low[10] >= Low[1]);
}

//+------------------------------------------------------------------+
//| Check Sell Signal                                                |
//+------------------------------------------------------------------+
bool CheckSellSignal()
{
    return (Open[1] > Close[6] &&
            High[9] <= Close[3] &&
            Low[10] <= Low[1]);
}

//+------------------------------------------------------------------+
//| Open Buy Order                                                   |
//+------------------------------------------------------------------+
void OpenBuyOrder()
{
    double price = Ask;
    double sl = price - (atrValue * SL_Multiplier);
    double tp = price + (atrValue * TP_Multiplier);
    
    sl = NormalizeDouble(sl, Digits);
    tp = NormalizeDouble(tp, Digits);
    
    int ticket = OrderSend(Symbol(), OP_BUY, LotSize, price, 3, sl, tp, 
                          TradeComment, MagicNumber, 0, clrGreen);
    
    if(ticket > 0)
    {
        Print("Buy order opened at ", price, " SL: ", sl, " TP: ", tp);
    }
    else
    {
        Print("Error opening buy order: ", GetLastError());
    }
}

//+------------------------------------------------------------------+
//| Open Sell Order                                                  |
//+------------------------------------------------------------------+
void OpenSellOrder()
{
    double price = Bid;
    double sl = price + (atrValue * SL_Multiplier);
    double tp = price - (atrValue * TP_Multiplier);
    
    sl = NormalizeDouble(sl, Digits);
    tp = NormalizeDouble(tp, Digits);
    
    int ticket = OrderSend(Symbol(), OP_SELL, LotSize, price, 3, sl, tp, 
                          TradeComment, MagicNumber, 0, clrRed);
    
    if(ticket > 0)
    {
        Print("Sell order opened at ", price, " SL: ", sl, " TP: ", tp);
    }
    else
    {
        Print("Error opening sell order: ", GetLastError());
    }
}
//+------------------------------------------------------------------+
