//+------------------------------------------------------------------+
//|                                           Strategy_EURUSD.mq5 |
//|                                  Generated by Strategy Converter |
//+------------------------------------------------------------------+
#property copyright "FxMath Quant"
#property link      "https://fxmath.com"
#property version   "1.00"

#include <Trade\Trade.mqh>

// Input Parameters
input double LotSize = 0.01;              // Lot Size
input int    ATR_Period = 30;   // ATR Period
input double SL_Multiplier = 4.79;  // Stop Loss Multiplier
input double TP_Multiplier = 8.10;  // Take Profit Multiplier
input int    MagicNumber = 12345;         // Magic Number
input string TradeComment = "Strategy_EURUSD";  // Trade Comment

// Global Variables
CTrade trade;
int atrHandle;
double atrBuffer[];

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{
    // Set trade parameters
    trade.SetExpertMagicNumber(MagicNumber);
    trade.SetDeviationInPoints(10);
    trade.SetTypeFilling(ORDER_FILLING_FOK);
    
    // Create ATR indicator handle
    atrHandle = iATR(_Symbol, PERIOD_CURRENT, ATR_Period);
    
    if(atrHandle == INVALID_HANDLE)
    {
        Print("Error creating ATR indicator");
        return(INIT_FAILED);
    }
    
    ArraySetAsSeries(atrBuffer, true);
    
    Print("Strategy EA initialized for EURUSD");
    return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
    if(atrHandle != INVALID_HANDLE)
        IndicatorRelease(atrHandle);
    
    Print("Strategy EA deinitialized");
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{
    // Copy ATR values
    if(CopyBuffer(atrHandle, 0, 0, 2, atrBuffer) < 2)
    {
        Print("Error copying ATR buffer");
        return;
    }
    
    double atrValue = atrBuffer[1];
    
    // Check if we have an open position
    if(!PositionSelect(_Symbol))
    {
        // No position - check for entry signals
        
        // Check Buy Signal
        if(CheckBuySignal())
        {
            OpenBuyOrder(atrValue);
        }
        // Check Sell Signal
        else if(CheckSellSignal())
        {
            OpenSellOrder(atrValue);
        }
    }
}

//+------------------------------------------------------------------+
//| Check Buy Signal                                                 |
//+------------------------------------------------------------------+
bool CheckBuySignal()
{
    // FIXED: Now uses proper MQL5 functions instead of array indexing
    return (iOpen(_Symbol, PERIOD_CURRENT, 1) < iClose(_Symbol, PERIOD_CURRENT, 6) &&
            iHigh(_Symbol, PERIOD_CURRENT, 9) >= iClose(_Symbol, PERIOD_CURRENT, 3) &&
            iLow(_Symbol, PERIOD_CURRENT, 10) >= iLow(_Symbol, PERIOD_CURRENT, 1));
}

//+------------------------------------------------------------------+
//| Check Sell Signal                                                |
//+------------------------------------------------------------------+
bool CheckSellSignal()
{
    // FIXED: Now uses proper MQL5 functions instead of array indexing
    return (iOpen(_Symbol, PERIOD_CURRENT, 1) > iClose(_Symbol, PERIOD_CURRENT, 6) &&
            iHigh(_Symbol, PERIOD_CURRENT, 9) <= iClose(_Symbol, PERIOD_CURRENT, 3) &&
            iLow(_Symbol, PERIOD_CURRENT, 10) <= iLow(_Symbol, PERIOD_CURRENT, 1));
}

//+------------------------------------------------------------------+
//| Open Buy Order                                                   |
//+------------------------------------------------------------------+
void OpenBuyOrder(double atrValue)
{
    double price = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
    double sl = price - (atrValue * SL_Multiplier);
    double tp = price + (atrValue * TP_Multiplier);
    
    sl = NormalizeDouble(sl, _Digits);
    tp = NormalizeDouble(tp, _Digits);
    
    if(trade.Buy(LotSize, _Symbol, price, sl, tp, TradeComment))
    {
        Print("Buy order opened at ", price, " SL: ", sl, " TP: ", tp);
    }
    else
    {
        Print("Error opening buy order: ", GetLastError());
    }
}

//+------------------------------------------------------------------+
//| Open Sell Order                                                  |
//+------------------------------------------------------------------+
void OpenSellOrder(double atrValue)
{
    double price = SymbolInfoDouble(_Symbol, SYMBOL_BID);
    double sl = price + (atrValue * SL_Multiplier);
    double tp = price - (atrValue * TP_Multiplier);
    
    sl = NormalizeDouble(sl, _Digits);
    tp = NormalizeDouble(tp, _Digits);
    
    if(trade.Sell(LotSize, _Symbol, price, sl, tp, TradeComment))
    {
        Print("Sell order opened at ", price, " SL: ", sl, " TP: ", tp);
    }
    else
    {
        Print("Error opening sell order: ", GetLastError());
    }
}
//+------------------------------------------------------------------+
